# Generated by Django 5.2.3 on 2025-06-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
    ]
